import React from 'react'

export const About = () => {
  return (
    <div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi minima voluptatum culpa quidem fugit fuga in, dignissimos excepturi maxime nulla exercitationem repellendus harum vitae distinctio tempora, veniam assumenda perspiciatis velit unde nobis. Tenetur, numquam officia? Amet nesciunt tenetur recusandae sit possimus deleniti expedita veniam, mollitia similique minus ipsam officia iste sed labore laboriosam dolorem hic, tempora dignissimos incidunt maxime eligendi assumenda qui saepe. Quisquam minus neque cumque odio fuga non! Cupiditate dolore eligendi explicabo et sint rem accusantium, repudiandae iure dolor expedita molestiae. Amet iste recusandae neque esse ipsam, rerum nihil dolores adipisci illo consectetur sequi quo minima commodi eius.</div>
      <br />
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi minima voluptatum culpa quidem fugit fuga in, dignissimos excepturi maxime nulla exercitationem repellendus harum vitae distinctio tempora, veniam assumenda perspiciatis velit unde nobis. Tenetur, numquam officia? Amet nesciunt tenetur recusandae sit possimus deleniti expedita veniam, mollitia similique minus ipsam officia iste sed labore laboriosam dolorem hic, tempora dignissimos incidunt maxime eligendi assumenda qui saepe. Quisquam minus neque cumque odio fuga non! Cupiditate dolore eligendi explicabo et sint rem accusantium, repudiandae iure dolor expedita molestiae. Amet iste recusandae neque esse ipsam, rerum nihil dolores adipisci illo consectetur sequi quo minima commodi eius.</div>
      <br />
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi minima voluptatum culpa quidem fugit fuga in, dignissimos excepturi maxime nulla exercitationem repellendus harum vitae distinctio tempora, veniam assumenda perspiciatis velit unde nobis. Tenetur, numquam officia? Amet nesciunt tenetur recusandae sit possimus deleniti expedita veniam, mollitia similique minus ipsam officia iste sed labore laboriosam dolorem hic, tempora dignissimos incidunt maxime eligendi assumenda qui saepe. Quisquam minus neque cumque odio fuga non! Cupiditate dolore eligendi explicabo et sint rem accusantium, repudiandae iure dolor expedita molestiae. Amet iste recusandae neque esse ipsam, rerum nihil dolores adipisci illo consectetur sequi quo minima commodi eius.</div>
      <br />
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi minima voluptatum culpa quidem fugit fuga in, dignissimos excepturi maxime nulla exercitationem repellendus harum vitae distinctio tempora, veniam assumenda perspiciatis velit unde nobis. Tenetur, numquam officia? Amet nesciunt tenetur recusandae sit possimus deleniti expedita veniam, mollitia similique minus ipsam officia iste sed labore laboriosam dolorem hic, tempora dignissimos incidunt maxime eligendi assumenda qui saepe. Quisquam minus neque cumque odio fuga non! Cupiditate dolore eligendi explicabo et sint rem accusantium, repudiandae iure dolor expedita molestiae. Amet iste recusandae neque esse ipsam, rerum nihil dolores adipisci illo consectetur sequi quo minima commodi eius.</div>
      <br />
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi minima voluptatum culpa quidem fugit fuga in, dignissimos excepturi maxime nulla exercitationem repellendus harum vitae distinctio tempora, veniam assumenda perspiciatis velit unde nobis. Tenetur, numquam officia? Amet nesciunt tenetur recusandae sit possimus deleniti expedita veniam, mollitia similique minus ipsam officia iste sed labore laboriosam dolorem hic, tempora dignissimos incidunt maxime eligendi assumenda qui saepe. Quisquam minus neque cumque odio fuga non! Cupiditate dolore eligendi explicabo et sint rem accusantium, repudiandae iure dolor expedita molestiae. Amet iste recusandae neque esse ipsam, rerum nihil dolores adipisci illo consectetur sequi quo minima commodi eius.</div>
      <br />
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi minima voluptatum culpa quidem fugit fuga in, dignissimos excepturi maxime nulla exercitationem repellendus harum vitae distinctio tempora, veniam assumenda perspiciatis velit unde nobis. Tenetur, numquam officia? Amet nesciunt tenetur recusandae sit possimus deleniti expedita veniam, mollitia similique minus ipsam officia iste sed labore laboriosam dolorem hic, tempora dignissimos incidunt maxime eligendi assumenda qui saepe. Quisquam minus neque cumque odio fuga non! Cupiditate dolore eligendi explicabo et sint rem accusantium, repudiandae iure dolor expedita molestiae. Amet iste recusandae neque esse ipsam, rerum nihil dolores adipisci illo consectetur sequi quo minima commodi eius.</div>
      <br />
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi minima voluptatum culpa quidem fugit fuga in, dignissimos excepturi maxime nulla exercitationem repellendus harum vitae distinctio tempora, veniam assumenda perspiciatis velit unde nobis. Tenetur, numquam officia? Amet nesciunt tenetur recusandae sit possimus deleniti expedita veniam, mollitia similique minus ipsam officia iste sed labore laboriosam dolorem hic, tempora dignissimos incidunt maxime eligendi assumenda qui saepe. Quisquam minus neque cumque odio fuga non! Cupiditate dolore eligendi explicabo et sint rem accusantium, repudiandae iure dolor expedita molestiae. Amet iste recusandae neque esse ipsam, rerum nihil dolores adipisci illo consectetur sequi quo minima commodi eius.</div>
      <br />
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi minima voluptatum culpa quidem fugit fuga in, dignissimos excepturi maxime nulla exercitationem repellendus harum vitae distinctio tempora, veniam assumenda perspiciatis velit unde nobis. Tenetur, numquam officia? Amet nesciunt tenetur recusandae sit possimus deleniti expedita veniam, mollitia similique minus ipsam officia iste sed labore laboriosam dolorem hic, tempora dignissimos incidunt maxime eligendi assumenda qui saepe. Quisquam minus neque cumque odio fuga non! Cupiditate dolore eligendi explicabo et sint rem accusantium, repudiandae iure dolor expedita molestiae. Amet iste recusandae neque esse ipsam, rerum nihil dolores adipisci illo consectetur sequi quo minima commodi eius.</div>
      <br />
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi minima voluptatum culpa quidem fugit fuga in, dignissimos excepturi maxime nulla exercitationem repellendus harum vitae distinctio tempora, veniam assumenda perspiciatis velit unde nobis. Tenetur, numquam officia? Amet nesciunt tenetur recusandae sit possimus deleniti expedita veniam, mollitia similique minus ipsam officia iste sed labore laboriosam dolorem hic, tempora dignissimos incidunt maxime eligendi assumenda qui saepe. Quisquam minus neque cumque odio fuga non! Cupiditate dolore eligendi explicabo et sint rem accusantium, repudiandae iure dolor expedita molestiae. Amet iste recusandae neque esse ipsam, rerum nihil dolores adipisci illo consectetur sequi quo minima commodi eius.</div>
      <br />
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi minima voluptatum culpa quidem fugit fuga in, dignissimos excepturi maxime nulla exercitationem repellendus harum vitae distinctio tempora, veniam assumenda perspiciatis velit unde nobis. Tenetur, numquam officia? Amet nesciunt tenetur recusandae sit possimus deleniti expedita veniam, mollitia similique minus ipsam officia iste sed labore laboriosam dolorem hic, tempora dignissimos incidunt maxime eligendi assumenda qui saepe. Quisquam minus neque cumque odio fuga non! Cupiditate dolore eligendi explicabo et sint rem accusantium, repudiandae iure dolor expedita molestiae. Amet iste recusandae neque esse ipsam, rerum nihil dolores adipisci illo consectetur sequi quo minima commodi eius.</div>
      <br />
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi minima voluptatum culpa quidem fugit fuga in, dignissimos excepturi maxime nulla exercitationem repellendus harum vitae distinctio tempora, veniam assumenda perspiciatis velit unde nobis. Tenetur, numquam officia? Amet nesciunt tenetur recusandae sit possimus deleniti expedita veniam, mollitia similique minus ipsam officia iste sed labore laboriosam dolorem hic, tempora dignissimos incidunt maxime eligendi assumenda qui saepe. Quisquam minus neque cumque odio fuga non! Cupiditate dolore eligendi explicabo et sint rem accusantium, repudiandae iure dolor expedita molestiae. Amet iste recusandae neque esse ipsam, rerum nihil dolores adipisci illo consectetur sequi quo minima commodi eius.</div>
      <br />
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi minima voluptatum culpa quidem fugit fuga in, dignissimos excepturi maxime nulla exercitationem repellendus harum vitae distinctio tempora, veniam assumenda perspiciatis velit unde nobis. Tenetur, numquam officia? Amet nesciunt tenetur recusandae sit possimus deleniti expedita veniam, mollitia similique minus ipsam officia iste sed labore laboriosam dolorem hic, tempora dignissimos incidunt maxime eligendi assumenda qui saepe. Quisquam minus neque cumque odio fuga non! Cupiditate dolore eligendi explicabo et sint rem accusantium, repudiandae iure dolor expedita molestiae. Amet iste recusandae neque esse ipsam, rerum nihil dolores adipisci illo consectetur sequi quo minima commodi eius.</div>
      <br />
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi minima voluptatum culpa quidem fugit fuga in, dignissimos excepturi maxime nulla exercitationem repellendus harum vitae distinctio tempora, veniam assumenda perspiciatis velit unde nobis. Tenetur, numquam officia? Amet nesciunt tenetur recusandae sit possimus deleniti expedita veniam, mollitia similique minus ipsam officia iste sed labore laboriosam dolorem hic, tempora dignissimos incidunt maxime eligendi assumenda qui saepe. Quisquam minus neque cumque odio fuga non! Cupiditate dolore eligendi explicabo et sint rem accusantium, repudiandae iure dolor expedita molestiae. Amet iste recusandae neque esse ipsam, rerum nihil dolores adipisci illo consectetur sequi quo minima commodi eius.</div>
      <br />
    </div>
    
  )

}
